[package]
name = "swim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Emulation Core
strum = "0.24"
strum_macros = "0.24"

# UI
gloo = {version = "0.8.0", features = ["futures"]}
monaco = { git = "https://github.com/siku2/rust-monaco", rev = "cac3ea13d4467966ac3d969d5b9c3c949209f637", features = ["yew-components"]  }
stylist = {version = "0.12.0", features = ["yew", "parser"]}
wasm-bindgen = "0.2.83"
web-sys = {version = "0.3.60", features = ["Event", "HtmlInputElement"]}
yew = {version = "0.20.0", features = ["csr"] }
wasm-bindgen-futures = "0.4.33"