[package]
name = "swim"
version = "0.1.0"
edition = "2021"
rust-version = "1.67"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Emulation Core
strum = "0.24"
strum_macros = "0.24"

# UI
gloo = {version = "0.8.0", features = ["futures"]}
monaco = { git = "https://github.com/b0x-Cub3d/rust-monaco", rev = "2910753bda2f2091f8d417e34b37a395bee61388", features = ["yew-components"]  }
stylist = {version = "0.12.0", features = ["yew", "parser"]}
wasm-bindgen = "0.2.83"
web-sys = {version = "0.3.60", features = ["Event", "HtmlInputElement"]}
js-sys = "0.3.60"
yew = {version = "0.20.0", features = ["csr"] }
wasm-bindgen-futures = "0.4.33"