[package]
name = "swim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monaco = { git = "https://github.com/siku2/rust-monaco", rev = "5684979fd326c875d6ee57306b243219fc38ff46" }
strum = "0.24"
strum_macros = "0.24"
yew = "0.19"
