name: Check

on:
  pull_request:

  # Allow these checks to be called by other workflows
  workflow_call:

env:
  PROJECT_TRUNK_VERSION: 'v0.16.0'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1

    - uses: Swatinem/rust-cache@v2

    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: ${{ env.PROJECT_TRUNK_VERSION }}

    - name: Set up build WASM target
      run: rustup target add wasm32-unknown-unknown

    - name: Run cargo fmt
      run: cargo fmt -- --check

    - name: Run clippy
      run: cargo clippy --no-deps --tests -- --deny warnings

    - name: Build
      run: trunk build
    
    - name: Check documentation
      run: cargo doc --no-deps

    - name: Run tests
      run: cargo test
