name: Check

on:
  pull_request:

  # Allow these checks to be called by other workflows
  workflow_call:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - uses: Swatinem/rust-cache@v2

    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'

    - name: Set up build WASM target
      run: rustup target add wasm32-unknown-unknown

    - name: Run cargo fmt
      run: cargo fmt -- --check

    - name: Run clippy
      run: cargo clippy --no-deps --tests -- --deny warnings

    - name: Build
      run: trunk build

    - name: Run tests
      run: cargo test
