name: Check

on:
  pull_request:

  # Allow these checks to be called by other workflows
  workflow_call:

env:
  PROJECT_TRUNK_VERSION: 'v0.18.8'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: Swatinem/rust-cache@v2

    - name: Install Rust
      run: rustup show

    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: ${{ env.PROJECT_TRUNK_VERSION }}

    - name: Run cargo fmt
      run: cargo fmt -- --check

    - name: Run clippy
      run: cargo clippy --no-deps --tests -- --deny warnings
      if: success() || failure()

    - name: Build
      run: trunk build
      if: success() || failure()

    - name: Check documentation
      run: cargo doc --no-deps
      if: success() || failure()

    - name: Run tests
      run: cargo test
      if: success() || failure()
