name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Specify the primary crate of the project.
  RUST_PRIMARY_CRATE: swim

jobs:
  check:
    uses: ./.github/workflows/check.yml

  build-deploy:
    name: Build and Deploy
    needs: check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - uses: Swatinem/rust-cache@v2

    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'

    - name: Set up build WASM target
      run: rustup target add wasm32-unknown-unknown

    - name: Build
      run: trunk build --release --public-url /${{ github.event.repository.name }}
    
    - name: Create documentation
      run: cargo doc --release

    - name: Merge documentation
      run: |
        rm -rf ./dist/docs
        echo "<meta http-equiv=\"refresh\" content=\"0; url=$RUST_PRIMARY_CRATE\">" > ./target/doc/index.html
        mkdir ./dist/docs
        cp -r ./target/doc ./dist

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
